apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ci-cd-app-pvc
spec:
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-app
  labels:
    app: ci-cd-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ci-cd-app
  template:
    metadata:
      labels:
        app: ci-cd-app
    spec:
      containers:
      - name: ci-cd-app
        image: 997909799/ci-cd-k8s:latest
        imagePullPolicy: Always
        env:
          - name: GIN_MODE
            value: 'release'
          - name: DATA_DIR
            value: '/data'
        volumeMounts:
          - name: ci-cd-app-vol
            mountPath: /data
        resources:
          limits:
            memory: "128Mi"
            cpu: "300m"
        ports:
        - containerPort: 8083

---
apiVersion: v1
kind: Service
metadata:
  name: ci-cd-app-svc
  namespace: ci-cd-app
spec:
  selector:
    app: ci-cd-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  type: LoadBalancer
