apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-cd-app
  namespace: default
spec:
  project: default

  source:
    path: ci-cd-app
    repoURL: 'https://github.com/JustinNguyen9979/CI-CD-K8s.git'
    targetRevision: HEAD
  destination:
    name: ''
    namespace: ci-cd-app
    server: 'https://kubernetes.default.svc'

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

# apiVersion: v1
# kind: Namespace
# metadata:
#   name: app-demo
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: app-demo-deploy
#   namespace: app-demo
# spec:
#   replicas: 1
#   selector:
#     matchLabels: 
#       app: app-demo
#   template:
#     metadata:
#       labels:
#         app: app-demo
#     spec:
#       containers:
#       - name: app-demo
#         image: nginx
#         ports:
#         - name: web
#           containerPort: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: cd-cd-k8s-svc
#   namespace: app-demo
#   labels:
#     app: app-demo
# spec:
#   type: ClusterIP
#   ports:
#   - name:  http
#     port:  80
#     targetPort: 80
#     protocol: TCP
#   selector:
#     app: app-demo
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: app-demo-ingress
#   namespace: app-demo
# spec:
#   rules:
#   - host: "app-demo.kienle.xyz"
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: app-demo-svc 
#             port:
#               number: 80
#   tls:
#   - hosts:
#     - app-demo.kienle.xyz
#     secretName: app-demo-tls-secret              
# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: app-demo-cert
#   namespace: app-demo
# spec:
#   secretName: app-demo-tls-secret
#   issuerRef:
#     name: letsencrypt-production
#     kind: ClusterIssuer
#   commonName: "app-demo.kienle.xyz"
#   dnsNames:
#     - "app-demo.kienle.xyz"